name: clone workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: clone 
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.host}}
          username: ${{secrets.username}}
          password: ${{secrets.password}}
          port: ${{secrets.port}}
          script: |
              ssh-keyscan -H github.com > ~/.ssh/known_hosts
              git clone https://github.com/dbordone/cmsc389T-web-template.git
