name: delete workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Delete
    runs-on: ubuntu-latest
    steps:
      - name: delete
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.host}}
          username: ${{secrets.username}}
          password: ${{secrets.password}}
          port: ${{secrets.port}}
          script: |
              unalias rm
              rm -rf cmsc389T-web-template
